//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modding_Assistant.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modding_Assistant.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mod error.
        /// </summary>
        public static string AddModErrorHeader {
            get {
                return ResourceManager.GetString("AddModErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add mod.
        /// </summary>
        public static string AddModErrorMessage {
            get {
                return ResourceManager.GetString("AddModErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ContextMenuCopy {
            get {
                return ResourceManager.GetString("ContextMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From file....
        /// </summary>
        public static string ContextMenuFromFile {
            get {
                return ResourceManager.GetString("ContextMenuFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move....
        /// </summary>
        public static string ContextMenuMove {
            get {
                return ResourceManager.GetString("ContextMenuMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string ContextMenuSelectAll {
            get {
                return ResourceManager.GetString("ContextMenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string DatabaseErrorHeader {
            get {
                return ResourceManager.GetString("DatabaseErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load mods list.
        /// </summary>
        public static string DatabaseErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string DataGridHeaderDependencies {
            get {
                return ResourceManager.GetString("DataGridHeaderDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DataGridHeaderDescription {
            get {
                return ResourceManager.GetString("DataGridHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Instructions.
        /// </summary>
        public static string DataGridHeaderInstallInstructions {
            get {
                return ResourceManager.GetString("DataGridHeaderInstallInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string DataGridHeaderLastUpdated {
            get {
                return ResourceManager.GetString("DataGridHeaderLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod File Name.
        /// </summary>
        public static string DataGridHeaderModRawName {
            get {
                return ResourceManager.GetString("DataGridHeaderModRawName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataGridHeaderName {
            get {
                return ResourceManager.GetString("DataGridHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string DataGridHeaderOrder {
            get {
                return ResourceManager.GetString("DataGridHeaderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Issues.
        /// </summary>
        public static string DataGridHeaderPotentialIssues {
            get {
                return ResourceManager.GetString("DataGridHeaderPotentialIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string DataGridHeaderURL {
            get {
                return ResourceManager.GetString("DataGridHeaderURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string DataGridHeaderVersion {
            get {
                return ResourceManager.GetString("DataGridHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string DefaultExcelName {
            get {
                return ResourceManager.GetString("DefaultExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete error.
        /// </summary>
        public static string DeleteModErrorHeader {
            get {
                return ResourceManager.GetString("DeleteModErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete mods.
        /// </summary>
        public static string DeleteModErrorMessage {
            get {
                return ResourceManager.GetString("DeleteModErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create file.
        /// </summary>
        public static string ExportErrorMessage {
            get {
                return ResourceManager.GetString("ExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful!.
        /// </summary>
        public static string ExportSuccessMessage {
            get {
                return ResourceManager.GetString("ExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export warning.
        /// </summary>
        public static string ExportWarningHeader {
            get {
                return ResourceManager.GetString("ExportWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mods to export.
        /// </summary>
        public static string ExportWarningMessage {
            get {
                return ResourceManager.GetString("ExportWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move file.
        /// </summary>
        public static string FromFileMoveError {
            get {
                return ResourceManager.GetString("FromFileMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import error.
        /// </summary>
        public static string ImportErrorHeader {
            get {
                return ResourceManager.GetString("ImportErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import mod.
        /// </summary>
        public static string ImportErrorMessage {
            get {
                return ResourceManager.GetString("ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MoveDialogCancelButton {
            get {
                return ResourceManager.GetString("MoveDialogCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the mod number before which to move the selected items:.
        /// </summary>
        public static string MoveDialogInputPrompt {
            get {
                return ResourceManager.GetString("MoveDialogInputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MoveDialogOkButton {
            get {
                return ResourceManager.GetString("MoveDialogOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move error.
        /// </summary>
        public static string MoveModErrorHeader {
            get {
                return ResourceManager.GetString("MoveModErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move mods.
        /// </summary>
        public static string MoveModErrorMessage {
            get {
                return ResourceManager.GetString("MoveModErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save changes to database.
        /// </summary>
        public static string SaveChangesDatabaseErrorMessage {
            get {
                return ResourceManager.GetString("SaveChangesDatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error.
        /// </summary>
        public static string SaveChangesErrorHeader {
            get {
                return ResourceManager.GetString("SaveChangesErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while saving.
        /// </summary>
        public static string SaveChangesUnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("SaveChangesUnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mod archive.
        /// </summary>
        public static string SelectArchivePrompt {
            get {
                return ResourceManager.GetString("SelectArchivePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mods folder.
        /// </summary>
        public static string SelectFolderPrompt {
            get {
                return ResourceManager.GetString("SelectFolderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during application startup. Please check the logs for more details..
        /// </summary>
        public static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup error.
        /// </summary>
        public static string StartupErrorHeader {
            get {
                return ResourceManager.GetString("StartupErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessHeader {
            get {
                return ResourceManager.GetString("SuccessHeader", resourceCulture);
            }
        }
    }
}
